import type { Venue, Window } from "./types";
import { normalizeSeed, type SeedVenue } from "./normalize";
import { SEED_STORIES } from "./stories";

/**
 * SEED DATA — every entry is `verified: false`.
 *
 * These are real, well-known NYC places seeded from general reputation so the
 * product can be felt before the curation pass. Attributes, windows, "the catch"
 * and Takes are illustrative drafts: verify each one (visit, check hours on the
 * venue's own site/Instagram) and flip `verified` before launch. Nothing here is
 * copied from another publication.
 *
 * Photo fields are placeholder gradients until ROUND's own photography exists.
 */

const P = {
  ink: { from: "#16213a", to: "#2e4470", angle: 160 },
  night: { from: "#0f1b17", to: "#1f4a3c", angle: 200 },
  amber: { from: "#2b1d0c", to: "#8a6320", angle: 170 },
  wine: { from: "#2a0f1c", to: "#7a2444", angle: 150 },
  forest: { from: "#0c2419", to: "#1f5a3f", angle: 165 },
  slate: { from: "#161922", to: "#3a4150", angle: 180 },
  rose: { from: "#3a1a2a", to: "#8a3f5a", angle: 155 },
  sea: { from: "#0e2a3a", to: "#1f6a8a", angle: 175 },
  brass: { from: "#1c160a", to: "#6b5a1e", angle: 160 },
  plum: { from: "#1c1030", to: "#4a2a7a", angle: 165 },
} as const;

const W: Record<string, Window[]> = {
  everyNight: [{ days: [0, 1, 2, 3, 4, 5, 6], from: 18, to: 26 }],
  weekendLate: [
    { days: [4, 5, 6], from: 21, to: 27 },
    { days: [0, 1, 2, 3], from: 19, to: 25 },
  ],
  earlyEvening: [{ days: [0, 1, 2, 3, 4, 5, 6], from: 17, to: 23 }],
  dinner: [{ days: [0, 1, 2, 3, 4, 5, 6], from: 18, to: 23 }],
  cocktailHours: [{ days: [0, 1, 2, 3, 4, 5, 6], from: 19, to: 25 }],
  brooklynLate: [
    { days: [4, 5, 6], from: 21, to: 28 },
    { days: [0, 1, 2, 3], from: 19, to: 26 },
  ],
};

const bar = (v: Omit<SeedVenue, "kind" | "verified">): SeedVenue => ({ ...v, kind: "bar", verified: false });
const restaurant = (v: Omit<SeedVenue, "kind" | "verified">): SeedVenue => ({ ...v, kind: "restaurant", verified: false });

const RAW: SeedVenue[] = [
  // ───────────────────────── WEST VILLAGE ─────────────────────────
  bar({
    slug: "the-spaniard",
    attrs: { food: 0.7, sports: 0.3, social: 0.7, late: 0.8 },
    name: "The Spaniard",
    neighborhood: "west-village",
    address: "190 W 4th St, New York, NY 10014",
    lat: 40.7315, lng: -74.0016,
    take: "Crowded, social, and good if your group wants somewhere lively without going full club.",
    theCatch: "Gets packed on weekends; go early or expect to stand.",
    tags: ["Lively", "Groups", "Burgers"],
    vibe: { lively: 0.9, chill: 0.3, talk: 0.25 },
    groupFit: { two: 0.6, small: 0.85, mid: 0.95, big: 0.75 },
    dateFit: { first: 0.35, early: 0.5, longterm: 0.55 },
    price: 2, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.4,
    photo: P.amber, friendsBeen: 2,
  }),
  bar({
    slug: "employees-only",
    attrs: { late: 1, food: 0.6, upscale: 0.7 },
    name: "Employees Only",
    neighborhood: "west-village",
    address: "510 Hudson St, New York, NY 10014",
    lat: 40.7332, lng: -74.006,
    take: "Proper cocktails, late hours, and a room that gets louder and better as the night goes on.",
    theCatch: "A wait is normal after 10 on Friday and Saturday.",
    tags: ["Cocktails", "Late", "Lively"],
    vibe: { lively: 0.8, chill: 0.4, talk: 0.4 },
    groupFit: { two: 0.85, small: 0.8, mid: 0.6, big: 0.3 },
    dateFit: { first: 0.7, early: 0.85, longterm: 0.8 },
    price: 3, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.35,
    photo: P.brass, friendsBeen: 3,
  }),
  bar({
    slug: "dante-west-village",
    attrs: { happyHour: 0.5, outdoor: 0.6, wine: 0.6 },
    name: "Dante West Village",
    neighborhood: "west-village",
    address: "551 Hudson St, New York, NY 10014",
    lat: 40.7339, lng: -74.0066,
    take: "Negronis on a corner that feels like a film set; the date bar you suggest when you want to look like you know things.",
    theCatch: "Sidewalk seats go first; inside is calmer on weeknights.",
    tags: ["Cocktails", "Date", "Aperitivo"],
    vibe: { lively: 0.55, chill: 0.7, talk: 0.7 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.4, big: 0.15 },
    dateFit: { first: 0.9, early: 0.9, longterm: 0.8 },
    price: 3, capacity: "medium", bestWindows: W.cocktailHours, easyIn: 0.5,
    photo: P.rose, friendsBeen: 4,
  }),
  bar({
    slug: "bar-pisellino",
    attrs: { outdoor: 0.7, wine: 0.8 },
    name: "Bar Pisellino",
    neighborhood: "west-village",
    address: "52 Grove St, New York, NY 10014",
    lat: 40.7331, lng: -74.0037,
    take: "A tiny Italian bar for a spritz before dinner; standing-room charm, no plan required.",
    theCatch: "Small enough that four people is a crowd.",
    tags: ["Aperitivo", "Date", "Small"],
    vibe: { lively: 0.5, chill: 0.75, talk: 0.7 },
    groupFit: { two: 0.95, small: 0.55, mid: 0.2, big: 0.05 },
    dateFit: { first: 0.85, early: 0.8, longterm: 0.75 },
    price: 2, capacity: "tiny", bestWindows: W.earlyEvening, easyIn: 0.45,
    photo: P.wine, friendsBeen: 1,
  }),
  bar({
    slug: "little-branch",
    attrs: { liveMusic: 0.9, speakeasy: 0.8 },
    name: "Little Branch",
    neighborhood: "west-village",
    address: "20 7th Ave S, New York, NY 10014",
    lat: 40.7313, lng: -74.0034,
    take: "Down the stairs, live jazz, real cocktails, and a room that makes you talk quietly whether you meant to or not.",
    theCatch: "They seat you; on weekends the line forms early and moves slowly.",
    tags: ["Cocktails", "Jazz", "Can Actually Talk"],
    vibe: { lively: 0.3, chill: 0.8, talk: 0.9 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.3,
    photo: P.night, friendsBeen: 2,
  }),
  bar({
    slug: "the-happiest-hour",
    attrs: { social: 0.7, cocktails: 0.5, food: 0.6 },
    name: "The Happiest Hour",
    neighborhood: "west-village",
    address: "121 W 10th St, New York, NY 10011",
    lat: 40.7343, lng: -74.0,
    take: "Cheerful, loud, and easy: the bar you pick when six people need somewhere and nobody wants to think.",
    theCatch: "Weekend evenings get elbow-to-elbow; weeknights are the move.",
    tags: ["Lively", "Groups", "Easy"],
    vibe: { lively: 0.85, chill: 0.4, talk: 0.3 },
    groupFit: { two: 0.6, small: 0.85, mid: 0.9, big: 0.7 },
    dateFit: { first: 0.45, early: 0.5, longterm: 0.5 },
    price: 2, capacity: "medium", bestWindows: W.everyNight, easyIn: 0.5,
    photo: P.sea, friendsBeen: 2,
  }),
  bar({
    slug: "wilfie-and-nell",
    attrs: { sports: 0.4, food: 0.6 },
    name: "Wilfie & Nell",
    neighborhood: "west-village",
    address: "228 W 4th St, New York, NY 10014",
    lat: 40.7345, lng: -74.0022,
    take: "A proper pub with long tables and good pints; big groups are welcome and nobody is watching the door.",
    theCatch: "Tables turn slowly; send someone ahead to claim one.",
    tags: ["Pub", "Groups", "Beer"],
    vibe: { lively: 0.75, chill: 0.55, talk: 0.45 },
    groupFit: { two: 0.6, small: 0.8, mid: 0.9, big: 0.85 },
    dateFit: { first: 0.4, early: 0.5, longterm: 0.55 },
    price: 2, capacity: "large", bestWindows: W.everyNight, easyIn: 0.65,
    photo: P.forest, friendsBeen: 1,
  }),
  bar({
    slug: "fiddlesticks",
    attrs: { sports: 1, seating: 0.8, food: 0.7, cheap: 0.6 },
    name: "Fiddlesticks",
    neighborhood: "west-village",
    address: "56 Greenwich Ave, New York, NY 10011",
    lat: 40.735, lng: -74.0,
    take: "Two floors, lots of screens, big tables: the sports-and-groups bar that never makes you feel bad about being twelve people.",
    tags: ["Sports", "Groups", "Big"],
    vibe: { lively: 0.85, chill: 0.4, talk: 0.25 },
    groupFit: { two: 0.4, small: 0.7, mid: 0.9, big: 0.95 },
    dateFit: { first: 0.2, early: 0.3, longterm: 0.35 },
    price: 2, capacity: "large", bestWindows: W.everyNight, easyIn: 0.75,
    photo: P.slate,
  }),
  bar({
    slug: "fairfax",
    attrs: { wine: 1, food: 0.7, happyHour: 0.4 },
    name: "Fairfax",
    neighborhood: "west-village",
    address: "234 W 4th St, New York, NY 10014",
    lat: 40.7346, lng: -74.0025,
    take: "Living-room lighting, natural wine, and the kind of quiet that makes a second date feel like a fourth.",
    tags: ["Wine", "Date", "Can Actually Talk"],
    vibe: { lively: 0.3, chill: 0.9, talk: 0.9 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "small", bestWindows: W.earlyEvening, easyIn: 0.5,
    photo: P.brass, friendsBeen: 1,
  }),
  restaurant({
    slug: "via-carota",
    name: "Via Carota",
    neighborhood: "west-village",
    address: "51 Grove St, New York, NY 10014",
    lat: 40.7332, lng: -74.0035,
    take: "The West Village date dinner, full stop: Italian, candlelit, worth the wait it will absolutely have.",
    theCatch: "Walk-in only and the wait is real; put your name down and go to Pisellino next door.",
    tags: ["Italian", "Date", "Classic"],
    vibe: { lively: 0.6, chill: 0.6, talk: 0.65 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.75, early: 0.95, longterm: 0.95 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.2,
    photo: P.amber, friendsBeen: 5,
  }),
  restaurant({
    slug: "lartusi",
    name: "L'Artusi",
    neighborhood: "west-village",
    address: "228 W 10th St, New York, NY 10014",
    lat: 40.7338, lng: -74.0055,
    take: "Polished, buzzy, pasta you'll think about later; the reservation that says you planned this.",
    theCatch: "Book ahead, or try the bar seats and hope.",
    tags: ["Italian", "Date", "Buzzy"],
    vibe: { lively: 0.7, chill: 0.5, talk: 0.5 },
    groupFit: { two: 0.9, small: 0.75, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.7, early: 0.9, longterm: 0.9 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.25,
    photo: P.wine, friendsBeen: 3,
  }),
  restaurant({
    slug: "jeffreys-grocery",
    name: "Jeffrey's Grocery",
    neighborhood: "west-village",
    address: "172 Waverly Pl, New York, NY 10014",
    lat: 40.7343, lng: -74.0011,
    take: "Oysters at the bar, a corner that always looks lit for a movie, and a menu that behaves for a first date.",
    tags: ["Seafood", "Date", "Corner"],
    vibe: { lively: 0.6, chill: 0.6, talk: 0.65 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.35, big: 0.1 },
    dateFit: { first: 0.9, early: 0.85, longterm: 0.8 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.4,
    photo: P.sea, friendsBeen: 2,
  }),
  restaurant({
    slug: "antons",
    name: "Anton's",
    neighborhood: "west-village",
    address: "570 Hudson St, New York, NY 10014",
    lat: 40.7341, lng: -74.0067,
    take: "Old-school-feeling and warm, with steak-and-martini energy for a date that's past the small talk.",
    tags: ["Classic", "Date", "Martinis"],
    vibe: { lively: 0.5, chill: 0.7, talk: 0.75 },
    groupFit: { two: 0.9, small: 0.75, mid: 0.4, big: 0.15 },
    dateFit: { first: 0.6, early: 0.85, longterm: 0.95 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.45,
    photo: P.brass, friendsBeen: 1,
  }),

  // ───────────────────────── EAST VILLAGE ─────────────────────────
  bar({
    slug: "death-and-co",
    attrs: { upscale: 0.7 },
    name: "Death & Co",
    neighborhood: "east-village",
    address: "433 E 6th St, New York, NY 10009",
    lat: 40.7256, lng: -73.9847,
    take: "The cocktail bar other cocktail bars copied; dark, serious, and still worth the wait for a date who cares.",
    theCatch: "Put your name in and expect a text later; it's not a walk-in on weekends.",
    tags: ["Cocktails", "Date", "Dark"],
    vibe: { lively: 0.45, chill: 0.7, talk: 0.75 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.2,
    photo: P.night, friendsBeen: 4,
  }),
  bar({
    slug: "amor-y-amargo",
    name: "Amor y Amargo",
    neighborhood: "east-village",
    address: "443 E 6th St, New York, NY 10009",
    lat: 40.7257, lng: -73.9844,
    take: "A closet-sized bitters bar where the bartender decides and you're better for it.",
    theCatch: "Room for maybe ten people; two is ideal, four is pushing it.",
    tags: ["Cocktails", "Tiny", "Can Actually Talk"],
    vibe: { lively: 0.3, chill: 0.8, talk: 0.85 },
    groupFit: { two: 0.95, small: 0.5, mid: 0.1, big: 0.0 },
    dateFit: { first: 0.8, early: 0.85, longterm: 0.8 },
    price: 3, capacity: "tiny", bestWindows: W.cocktailHours, easyIn: 0.35,
    photo: P.wine, friendsBeen: 1,
  }),
  bar({
    slug: "mister-paradise",
    attrs: { dance: 0.3, late: 0.8, social: 0.7 },
    name: "Mister Paradise",
    neighborhood: "east-village",
    address: "105 1st Ave, New York, NY 10003",
    lat: 40.7261, lng: -73.986,
    take: "Fun cocktails, a fun room, and a crowd that's here to have a night, not analyze one.",
    tags: ["Cocktails", "Lively", "Groups"],
    vibe: { lively: 0.85, chill: 0.4, talk: 0.35 },
    groupFit: { two: 0.7, small: 0.9, mid: 0.8, big: 0.4 },
    dateFit: { first: 0.6, early: 0.7, longterm: 0.6 },
    price: 2, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.5,
    photo: P.plum, friendsBeen: 3,
  }),
  bar({
    slug: "please-dont-tell",
    attrs: { speakeasy: 1, food: 0.6 },
    name: "Please Don't Tell",
    neighborhood: "east-village",
    address: "113 St Marks Pl, New York, NY 10009",
    lat: 40.7273, lng: -73.9838,
    take: "Through the phone booth in a hot dog shop; still the speakeasy move that lands on a date.",
    theCatch: "Reservations open same day and vanish; without one, you're not getting in.",
    tags: ["Speakeasy", "Cocktails", "Date"],
    vibe: { lively: 0.5, chill: 0.7, talk: 0.7 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.2, big: 0.0 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.75 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.1,
    photo: P.brass, friendsBeen: 2,
  }),
  bar({
    slug: "the-wayland",
    attrs: { liveMusic: 0.8, outdoor: 0.3, late: 0.8 },
    name: "The Wayland",
    neighborhood: "east-village",
    address: "700 E 9th St, New York, NY 10009",
    lat: 40.7264, lng: -73.9779,
    take: "Live music some nights, a crowd that spills onto the corner, and cocktails better than the noise suggests.",
    tags: ["Live Music", "Lively", "Corner"],
    vibe: { lively: 0.85, chill: 0.45, talk: 0.3 },
    groupFit: { two: 0.7, small: 0.85, mid: 0.7, big: 0.4 },
    dateFit: { first: 0.55, early: 0.7, longterm: 0.65 },
    price: 2, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.45,
    photo: P.amber, friendsBeen: 2,
  }),
  bar({
    slug: "niagara",
    attrs: { late: 1, cheap: 1, sports: 0.3, dance: 0.4 },
    name: "Niagara",
    neighborhood: "east-village",
    address: "112 Avenue A, New York, NY 10009",
    lat: 40.7261, lng: -73.9838,
    take: "A big, loud, unpretentious corner bar; the right answer when the plan is 'somewhere' and the group is large.",
    tags: ["Dive", "Groups", "Late"],
    vibe: { lively: 0.9, chill: 0.35, talk: 0.2 },
    groupFit: { two: 0.5, small: 0.75, mid: 0.9, big: 0.9 },
    dateFit: { first: 0.25, early: 0.4, longterm: 0.45 },
    price: 1, capacity: "large", bestWindows: W.weekendLate, easyIn: 0.7,
    photo: P.slate, friendsBeen: 1,
  }),
  bar({
    slug: "joyface",
    attrs: { dance: 0.4, late: 0.8 },
    name: "Joyface",
    neighborhood: "east-village",
    address: "513 E 5th St, New York, NY 10009",
    lat: 40.7247, lng: -73.9835,
    take: "Seventies wood paneling, good drinks, a room that wants you to stay: lively without being a scene.",
    tags: ["Cocktails", "Lively", "Retro"],
    vibe: { lively: 0.8, chill: 0.5, talk: 0.4 },
    groupFit: { two: 0.75, small: 0.9, mid: 0.75, big: 0.35 },
    dateFit: { first: 0.65, early: 0.75, longterm: 0.7 },
    price: 2, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.5,
    photo: P.brass, friendsBeen: 2,
  }),
  bar({
    slug: "von",
    attrs: { wine: 0.8, scene: 0.5 },
    name: "Von",
    neighborhood: "east-village",
    address: "3 Bleecker St, New York, NY 10012",
    lat: 40.7254, lng: -73.9924,
    take: "Low ceilings, wine and cocktails, cooler than it needs to be and quiet enough to hear yourself.",
    tags: ["Wine", "Can Actually Talk", "Cool"],
    vibe: { lively: 0.45, chill: 0.8, talk: 0.8 },
    groupFit: { two: 0.9, small: 0.75, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.85, early: 0.85, longterm: 0.8 },
    price: 2, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.55,
    photo: P.plum, friendsBeen: 1,
  }),
  restaurant({
    slug: "bar-primi",
    name: "Bar Primi",
    neighborhood: "east-village",
    address: "325 Bowery, New York, NY 10003",
    lat: 40.7255, lng: -73.9917,
    take: "Pasta on the Bowery with enough buzz to carry a first date and enough room to bring four.",
    tags: ["Italian", "Pasta", "Buzzy"],
    vibe: { lively: 0.7, chill: 0.5, talk: 0.55 },
    groupFit: { two: 0.9, small: 0.85, mid: 0.6, big: 0.3 },
    dateFit: { first: 0.85, early: 0.85, longterm: 0.75 },
    price: 2, capacity: "large", bestWindows: W.dinner, easyIn: 0.5,
    photo: P.amber, friendsBeen: 2,
  }),
  restaurant({
    slug: "emilios-ballato",
    name: "Emilio's Ballato",
    neighborhood: "east-village",
    address: "55 E Houston St, New York, NY 10012",
    lat: 40.7245, lng: -73.9948,
    take: "Old New York in a red-sauce frame; a date here feels like a scene from something.",
    theCatch: "No reservations to speak of and a line most nights; go early.",
    tags: ["Italian", "Old NYC", "Date"],
    vibe: { lively: 0.6, chill: 0.6, talk: 0.65 },
    groupFit: { two: 0.9, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.7, early: 0.9, longterm: 0.95 },
    price: 3, capacity: "small", bestWindows: W.dinner, easyIn: 0.2,
    photo: P.wine, friendsBeen: 1,
  }),

  // ───────────────────────── LOWER EAST SIDE ─────────────────────────
  bar({
    slug: "rays-bar",
    attrs: { scene: 0.8, social: 0.8, late: 1, dance: 0.3 },
    name: "Ray's Bar",
    neighborhood: "lower-east-side",
    address: "177 Chrystie St, New York, NY 10002",
    lat: 40.7218, lng: -73.993,
    take: "A dive with a guest list's worth of regulars; loud, fun, and exactly what a Thursday wants to be.",
    theCatch: "Tiny and popular; after 11 on weekends expect a line.",
    tags: ["Dive", "Lively", "Late"],
    vibe: { lively: 0.95, chill: 0.3, talk: 0.15 },
    groupFit: { two: 0.7, small: 0.85, mid: 0.6, big: 0.25 },
    dateFit: { first: 0.45, early: 0.65, longterm: 0.6 },
    price: 1, capacity: "small", bestWindows: W.weekendLate, easyIn: 0.3,
    photo: P.night, friendsBeen: 6,
  }),
  bar({
    slug: "attaboy",
    attrs: { speakeasy: 0.8 },
    name: "Attaboy",
    neighborhood: "lower-east-side",
    address: "134 Eldridge St, New York, NY 10002",
    lat: 40.7194, lng: -73.9912,
    take: "No menu; tell them what you like and let a great bartender do the rest. A date-night cheat code.",
    theCatch: "Ring the bell and wait; on weekends the wait is long and worth it once.",
    tags: ["Cocktails", "No Menu", "Date"],
    vibe: { lively: 0.45, chill: 0.75, talk: 0.7 },
    groupFit: { two: 0.95, small: 0.65, mid: 0.2, big: 0.0 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "tiny", bestWindows: W.cocktailHours, easyIn: 0.2,
    photo: P.brass, friendsBeen: 3,
  }),
  bar({
    slug: "the-flower-shop",
    attrs: { dance: 0.5, late: 0.9, food: 0.8, seating: 0.6 },
    name: "The Flower Shop",
    neighborhood: "lower-east-side",
    address: "107 Eldridge St, New York, NY 10002",
    lat: 40.7177, lng: -73.9917,
    take: "Dinner upstairs, a basement that turns into a party downstairs; bring the group and stay late.",
    theCatch: "The basement bar fills up fast on Fridays.",
    tags: ["Groups", "Lively", "Late"],
    vibe: { lively: 0.9, chill: 0.4, talk: 0.25 },
    groupFit: { two: 0.6, small: 0.85, mid: 0.95, big: 0.7 },
    dateFit: { first: 0.5, early: 0.6, longterm: 0.55 },
    price: 2, capacity: "large", bestWindows: W.weekendLate, easyIn: 0.5,
    photo: P.rose, friendsBeen: 4,
  }),
  bar({
    slug: "clandestino",
    attrs: { late: 1, social: 0.8, cheap: 0.9 },
    name: "Clandestino",
    neighborhood: "lower-east-side",
    address: "35 Canal St, New York, NY 10002",
    lat: 40.7144, lng: -73.9915,
    take: "Under the bridge, loud, cheap-ish, and always a crowd: the group bar that never asks questions.",
    tags: ["Dive", "Groups", "Lively"],
    vibe: { lively: 0.9, chill: 0.35, talk: 0.2 },
    groupFit: { two: 0.6, small: 0.8, mid: 0.9, big: 0.8 },
    dateFit: { first: 0.3, early: 0.5, longterm: 0.5 },
    price: 1, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.6,
    photo: P.slate, friendsBeen: 2,
  }),
  bar({
    slug: "mr-fongs",
    attrs: { dance: 0.5, late: 1, scene: 0.6 },
    name: "Mr. Fong's",
    neighborhood: "lower-east-side",
    address: "40 Market St, New York, NY 10002",
    lat: 40.7127, lng: -73.9946,
    take: "Neon, good drinks, a crowd that skews cool; lively enough for a group, dim enough for a date.",
    tags: ["Cocktails", "Lively", "Cool"],
    vibe: { lively: 0.8, chill: 0.5, talk: 0.4 },
    groupFit: { two: 0.8, small: 0.9, mid: 0.7, big: 0.35 },
    dateFit: { first: 0.65, early: 0.8, longterm: 0.7 },
    price: 2, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.45,
    photo: P.plum, friendsBeen: 2,
  }),
  bar({
    slug: "bar-goto",
    attrs: { food: 0.6 },
    name: "Bar Goto",
    neighborhood: "lower-east-side",
    address: "245 Eldridge St, New York, NY 10002",
    lat: 40.7218, lng: -73.9891,
    take: "Japanese precision, calm room, cocktails you'll remember; for two people who want to actually talk.",
    tags: ["Cocktails", "Calm", "Can Actually Talk"],
    vibe: { lively: 0.3, chill: 0.85, talk: 0.9 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.9, early: 0.85, longterm: 0.8 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.5,
    photo: P.sea, friendsBeen: 1,
  }),
  bar({
    slug: "the-back-room",
    attrs: { speakeasy: 1, late: 0.8 },
    name: "The Back Room",
    neighborhood: "lower-east-side",
    address: "102 Norfolk St, New York, NY 10002",
    lat: 40.7183, lng: -73.9865,
    take: "Drinks in teacups behind an unmarked door; a bit of theater that works for a group with something to celebrate.",
    tags: ["Speakeasy", "Groups", "Theatrical"],
    vibe: { lively: 0.75, chill: 0.5, talk: 0.35 },
    groupFit: { two: 0.7, small: 0.85, mid: 0.85, big: 0.55 },
    dateFit: { first: 0.6, early: 0.7, longterm: 0.6 },
    price: 2, capacity: "large", bestWindows: W.weekendLate, easyIn: 0.55,
    photo: P.wine, friendsBeen: 1,
  }),
  restaurant({
    slug: "cervos",
    name: "Cervo's",
    neighborhood: "lower-east-side",
    address: "43 Canal St, New York, NY 10002",
    lat: 40.7147, lng: -73.991,
    take: "Seafood, vinho verde, a narrow room with real energy; the date dinner for people who like their nights a little loud.",
    tags: ["Seafood", "Date", "Energy"],
    vibe: { lively: 0.75, chill: 0.45, talk: 0.5 },
    groupFit: { two: 0.9, small: 0.75, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.8, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "small", bestWindows: W.dinner, easyIn: 0.3,
    photo: P.sea, friendsBeen: 3,
  }),
  restaurant({
    slug: "kikis",
    attrs: { cheap: 0.5, social: 0.5 },
    name: "Kiki's",
    neighborhood: "lower-east-side",
    address: "130 Division St, New York, NY 10002",
    lat: 40.7141, lng: -73.9924,
    take: "Greek plates, big tables, a room that's always a bit of a party; better for four than for two.",
    theCatch: "No reservations and a wait most nights; groups should arrive early or patient.",
    tags: ["Greek", "Groups", "Lively"],
    vibe: { lively: 0.85, chill: 0.4, talk: 0.4 },
    groupFit: { two: 0.7, small: 0.9, mid: 0.85, big: 0.5 },
    dateFit: { first: 0.6, early: 0.7, longterm: 0.7 },
    price: 2, capacity: "medium", bestWindows: W.dinner, easyIn: 0.3,
    photo: P.forest, friendsBeen: 4,
  }),

  // ───────────────────────── SOHO & NOLITA ─────────────────────────
  bar({
    slug: "fanelli-cafe",
    attrs: { classic: 1, food: 0.6, beer: 0.8 },
    name: "Fanelli Cafe",
    neighborhood: "soho-nolita",
    address: "94 Prince St, New York, NY 10012",
    lat: 40.7241, lng: -73.9985,
    take: "One of the oldest bars in the city and it acts like it; a beer at the bar here is a whole personality.",
    tags: ["Old NYC", "Beer", "Chill"],
    vibe: { lively: 0.55, chill: 0.8, talk: 0.7 },
    groupFit: { two: 0.85, small: 0.8, mid: 0.5, big: 0.2 },
    dateFit: { first: 0.7, early: 0.75, longterm: 0.8 },
    price: 2, capacity: "medium", bestWindows: W.everyNight, easyIn: 0.55,
    photo: P.brass, friendsBeen: 2,
  }),
  bar({
    slug: "ear-inn",
    attrs: { classic: 1, liveMusic: 0.5, food: 0.6 },
    name: "Ear Inn",
    neighborhood: "soho-nolita",
    address: "326 Spring St, New York, NY 10013",
    lat: 40.7256, lng: -74.0093,
    take: "A crooked old house by the river with a bar that's outlasted every trend; go for the quiet, stay for the room.",
    tags: ["Old NYC", "Chill", "Can Actually Talk"],
    vibe: { lively: 0.4, chill: 0.9, talk: 0.8 },
    groupFit: { two: 0.85, small: 0.8, mid: 0.5, big: 0.2 },
    dateFit: { first: 0.7, early: 0.8, longterm: 0.85 },
    price: 2, capacity: "small", bestWindows: W.everyNight, easyIn: 0.6,
    photo: P.forest, friendsBeen: 1,
  }),
  bar({
    slug: "temple-bar",
    attrs: { upscale: 0.8, speakeasy: 0.4 },
    name: "Temple Bar",
    neighborhood: "soho-nolita",
    address: "332 Lafayette St, New York, NY 10012",
    lat: 40.7251, lng: -73.995,
    take: "Dark, plush, and grown-up; martinis in a room built for leaning in.",
    tags: ["Cocktails", "Date", "Dark"],
    vibe: { lively: 0.45, chill: 0.8, talk: 0.75 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.9 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.4,
    photo: P.night, friendsBeen: 2,
  }),
  bar({
    slug: "the-ship",
    attrs: { speakeasy: 0.6 },
    name: "The Ship",
    neighborhood: "soho-nolita",
    address: "158 Lafayette St, New York, NY 10013",
    lat: 40.7203, lng: -73.9998,
    take: "Down a staircase, nautical without being a theme, cocktails that reward ordering something you can't pronounce.",
    tags: ["Cocktails", "Date", "Below Street"],
    vibe: { lively: 0.5, chill: 0.75, talk: 0.7 },
    groupFit: { two: 0.9, small: 0.75, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.8, early: 0.85, longterm: 0.75 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.5,
    photo: P.sea, friendsBeen: 1,
  }),
  bar({
    slug: "sweet-and-vicious",
    attrs: { outdoor: 1, cheap: 0.8, late: 0.8 },
    name: "Sweet & Vicious",
    neighborhood: "soho-nolita",
    address: "5 Spring St, New York, NY 10012",
    lat: 40.7215, lng: -73.9948,
    take: "A backyard, cheap enough drinks, and a crowd that's fine with standing; the reliable group start.",
    tags: ["Backyard", "Groups", "Lively"],
    vibe: { lively: 0.85, chill: 0.45, talk: 0.3 },
    groupFit: { two: 0.55, small: 0.8, mid: 0.9, big: 0.8 },
    dateFit: { first: 0.4, early: 0.5, longterm: 0.5 },
    price: 1, capacity: "large", bestWindows: W.weekendLate, easyIn: 0.65,
    photo: P.forest, friendsBeen: 2,
  }),
  bar({
    slug: "spring-lounge",
    attrs: { happyHour: 0.7, classic: 0.7, late: 0.8 },
    name: "Spring Lounge",
    neighborhood: "soho-nolita",
    address: "48 Spring St, New York, NY 10012",
    lat: 40.7221, lng: -73.9956,
    take: "A corner dive that opens early and stays honest; groups spill onto the sidewalk and nobody minds.",
    tags: ["Dive", "Corner", "Groups"],
    vibe: { lively: 0.8, chill: 0.5, talk: 0.3 },
    groupFit: { two: 0.6, small: 0.8, mid: 0.85, big: 0.7 },
    dateFit: { first: 0.3, early: 0.45, longterm: 0.5 },
    price: 1, capacity: "medium", bestWindows: W.everyNight, easyIn: 0.7,
    photo: P.slate, friendsBeen: 1,
  }),
  restaurant({
    slug: "thai-diner",
    name: "Thai Diner",
    neighborhood: "soho-nolita",
    address: "186 Mott St, New York, NY 10012",
    lat: 40.7207, lng: -73.9956,
    take: "Loud, fun, delicious, and not remotely precious: the date dinner where nobody has to perform.",
    theCatch: "Waits are standard; put your name in and walk to Spring Lounge.",
    tags: ["Thai", "Fun", "Casual"],
    vibe: { lively: 0.8, chill: 0.45, talk: 0.45 },
    groupFit: { two: 0.9, small: 0.85, mid: 0.5, big: 0.15 },
    dateFit: { first: 0.85, early: 0.8, longterm: 0.75 },
    price: 2, capacity: "small", bestWindows: W.dinner, easyIn: 0.3,
    photo: P.amber, friendsBeen: 3,
  }),

  // ───────────────────────── TRIBECA ─────────────────────────
  bar({
    slug: "smith-and-mills",
    attrs: { classic: 0.6, upscale: 0.7 },
    name: "Smith & Mills",
    neighborhood: "tribeca",
    address: "71 N Moore St, New York, NY 10013",
    lat: 40.7198, lng: -74.0093,
    take: "A tiny carriage house with candlelight and cocktails; the definition of a two-person bar.",
    theCatch: "A handful of seats; a group of four is a stretch.",
    tags: ["Cocktails", "Tiny", "Date"],
    vibe: { lively: 0.4, chill: 0.85, talk: 0.8 },
    groupFit: { two: 0.95, small: 0.5, mid: 0.15, big: 0.0 },
    dateFit: { first: 0.9, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "tiny", bestWindows: W.cocktailHours, easyIn: 0.35,
    photo: P.brass, friendsBeen: 1,
  }),
  bar({
    slug: "weather-up",
    name: "Weather Up",
    neighborhood: "tribeca",
    address: "159 Duane St, New York, NY 10013",
    lat: 40.7168, lng: -74.0078,
    take: "White subway tile, low light, cocktails done properly; calm enough to hear the answer to a real question.",
    tags: ["Cocktails", "Date", "Calm"],
    vibe: { lively: 0.4, chill: 0.8, talk: 0.8 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.35, big: 0.05 },
    dateFit: { first: 0.85, early: 0.85, longterm: 0.8 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.5,
    photo: P.sea, friendsBeen: 1,
  }),
  bar({
    slug: "walkers",
    attrs: { classic: 0.8, food: 0.8, sports: 0.3 },
    name: "Walker's",
    neighborhood: "tribeca",
    address: "16 N Moore St, New York, NY 10013",
    lat: 40.7198, lng: -74.008,
    take: "A neighborhood tavern that's been there forever; big tables, burgers, and zero pretense for a group.",
    tags: ["Tavern", "Groups", "Chill"],
    vibe: { lively: 0.6, chill: 0.75, talk: 0.6 },
    groupFit: { two: 0.7, small: 0.85, mid: 0.85, big: 0.6 },
    dateFit: { first: 0.5, early: 0.6, longterm: 0.65 },
    price: 2, capacity: "large", bestWindows: W.everyNight, easyIn: 0.7,
    photo: P.forest,
  }),
  restaurant({
    slug: "the-odeon",
    name: "The Odeon",
    neighborhood: "tribeca",
    address: "145 W Broadway, New York, NY 10013",
    lat: 40.7169, lng: -74.0086,
    take: "The brasserie that's been the Tribeca date since before Tribeca was Tribeca; steak frites and a martini, done.",
    tags: ["Brasserie", "Classic", "Date"],
    vibe: { lively: 0.65, chill: 0.6, talk: 0.65 },
    groupFit: { two: 0.9, small: 0.85, mid: 0.6, big: 0.3 },
    dateFit: { first: 0.75, early: 0.85, longterm: 0.9 },
    price: 3, capacity: "large", bestWindows: W.dinner, easyIn: 0.5,
    photo: P.amber, friendsBeen: 2,
  }),
  restaurant({
    slug: "frenchette",
    name: "Frenchette",
    neighborhood: "tribeca",
    address: "241 W Broadway, New York, NY 10013",
    lat: 40.7196, lng: -74.0059,
    take: "French, glamorous, a little loud; the dinner that makes the whole night feel like an occasion.",
    theCatch: "Reserve well ahead; the bar is the walk-in play.",
    tags: ["French", "Occasion", "Buzzy"],
    vibe: { lively: 0.7, chill: 0.5, talk: 0.55 },
    groupFit: { two: 0.9, small: 0.8, mid: 0.5, big: 0.2 },
    dateFit: { first: 0.6, early: 0.85, longterm: 0.95 },
    price: 4, capacity: "medium", bestWindows: W.dinner, easyIn: 0.25,
    photo: P.wine, friendsBeen: 2,
  }),
  restaurant({
    slug: "tinys",
    name: "Tiny's & the Bar Upstairs",
    neighborhood: "tribeca",
    address: "135 W Broadway, New York, NY 10013",
    lat: 40.7165, lng: -74.0088,
    take: "A pink townhouse with a bar upstairs; dinner then drinks without leaving the building, which is a date in itself.",
    tags: ["American", "Date", "Townhouse"],
    vibe: { lively: 0.55, chill: 0.7, talk: 0.65 },
    groupFit: { two: 0.95, small: 0.75, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.8, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "small", bestWindows: W.dinner, easyIn: 0.4,
    photo: P.rose, friendsBeen: 1,
  }),

  // ───────────────────────── CHELSEA ─────────────────────────
  bar({
    slug: "bathtub-gin",
    attrs: { speakeasy: 1, groups: 0.6 },
    name: "Bathtub Gin",
    neighborhood: "chelsea",
    address: "132 9th Ave, New York, NY 10011",
    lat: 40.7429, lng: -74.0043,
    take: "Behind a coffee shop, gin-forward, a little theatrical; works for a date and for a table of six.",
    tags: ["Speakeasy", "Cocktails", "Groups"],
    vibe: { lively: 0.7, chill: 0.55, talk: 0.5 },
    groupFit: { two: 0.85, small: 0.85, mid: 0.7, big: 0.4 },
    dateFit: { first: 0.75, early: 0.8, longterm: 0.7 },
    price: 3, capacity: "medium", bestWindows: W.weekendLate, easyIn: 0.4,
    photo: P.brass, friendsBeen: 2,
  }),
  bar({
    slug: "gallow-green",
    attrs: { rooftop: 1, outdoor: 1, upscale: 0.8, dressy: 0.6 },
    name: "Gallow Green",
    neighborhood: "chelsea",
    address: "542 W 27th St, New York, NY 10001",
    lat: 40.7509, lng: -74.0053,
    take: "A rooftop garden on top of a theater; in warm months it's the most romantic room in Chelsea, and it's not a room.",
    theCatch: "Seasonal and reservation-driven; check before you walk over.",
    tags: ["Rooftop", "Date", "Seasonal"],
    vibe: { lively: 0.6, chill: 0.7, talk: 0.6 },
    groupFit: { two: 0.95, small: 0.8, mid: 0.5, big: 0.2 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.9 },
    price: 3, capacity: "medium", bestWindows: W.earlyEvening, easyIn: 0.3,
    photo: P.forest, friendsBeen: 2,
  }),
  bar({
    slug: "porchlight",
    attrs: { seating: 0.9, groups: 0.8 },
    name: "Porchlight",
    neighborhood: "chelsea",
    address: "271 11th Ave, New York, NY 10001",
    lat: 40.7521, lng: -74.0064,
    take: "Southern-leaning cocktails, a wide room, and space to actually seat a group on the far west side.",
    tags: ["Cocktails", "Groups", "Roomy"],
    vibe: { lively: 0.65, chill: 0.6, talk: 0.5 },
    groupFit: { two: 0.7, small: 0.85, mid: 0.9, big: 0.7 },
    dateFit: { first: 0.6, early: 0.7, longterm: 0.65 },
    price: 3, capacity: "large", bestWindows: W.everyNight, easyIn: 0.7,
    photo: P.amber, friendsBeen: 1,
  }),
  bar({
    slug: "the-tippler",
    attrs: { groups: 1, social: 0.7, happyHour: 0.7 },
    name: "The Tippler",
    neighborhood: "chelsea",
    address: "425 W 15th St, New York, NY 10011",
    lat: 40.7423, lng: -74.006,
    take: "Under Chelsea Market, big and brick-lined, built for the after-work group that grows by the hour.",
    tags: ["Groups", "Lively", "Underground"],
    vibe: { lively: 0.8, chill: 0.45, talk: 0.35 },
    groupFit: { two: 0.6, small: 0.8, mid: 0.9, big: 0.85 },
    dateFit: { first: 0.4, early: 0.5, longterm: 0.5 },
    price: 2, capacity: "large", bestWindows: W.everyNight, easyIn: 0.65,
    photo: P.slate, friendsBeen: 2,
  }),
  restaurant({
    slug: "cookshop",
    name: "Cookshop",
    neighborhood: "chelsea",
    address: "156 10th Ave, New York, NY 10011",
    lat: 40.7439, lng: -74.0054,
    take: "Bright, seasonal, unfussy; the Chelsea dinner that's easy to like and easy to book.",
    tags: ["American", "Seasonal", "Easy"],
    vibe: { lively: 0.6, chill: 0.65, talk: 0.65 },
    groupFit: { two: 0.85, small: 0.85, mid: 0.6, big: 0.3 },
    dateFit: { first: 0.8, early: 0.8, longterm: 0.75 },
    price: 3, capacity: "large", bestWindows: W.dinner, easyIn: 0.6,
    photo: P.forest, friendsBeen: 1,
  }),

  // ───────────────────────── WILLIAMSBURG ─────────────────────────
  bar({
    slug: "westlight",
    attrs: { rooftop: 1, upscale: 0.9, dressy: 0.7, scene: 0.6 },
    name: "Westlight",
    neighborhood: "williamsburg",
    address: "111 N 12th St, Brooklyn, NY 11249",
    lat: 40.7222, lng: -73.9576,
    take: "Twenty-two floors up with the whole skyline; a date here does half the talking for you.",
    theCatch: "Elevator lines on weekend nights; go on a weeknight for the view without the wait.",
    tags: ["Rooftop", "Views", "Date"],
    vibe: { lively: 0.7, chill: 0.55, talk: 0.5 },
    groupFit: { two: 0.95, small: 0.8, mid: 0.5, big: 0.2 },
    dateFit: { first: 0.9, early: 0.9, longterm: 0.8 },
    price: 3, capacity: "medium", bestWindows: W.cocktailHours, easyIn: 0.35,
    photo: P.ink, friendsBeen: 3,
  }),
  bar({
    slug: "union-pool",
    attrs: { dance: 0.7, liveMusic: 0.9, outdoor: 1, social: 0.9, late: 1, food: 0.6 },
    name: "Union Pool",
    neighborhood: "williamsburg",
    address: "484 Union Ave, Brooklyn, NY 11211",
    lat: 40.7139, lng: -73.9517,
    take: "A backyard, a taco truck, a band inside, and a crowd that came out to meet people; the group night that runs itself.",
    tags: ["Backyard", "Lively", "Groups"],
    vibe: { lively: 0.95, chill: 0.35, talk: 0.15 },
    groupFit: { two: 0.6, small: 0.85, mid: 0.95, big: 0.85 },
    dateFit: { first: 0.4, early: 0.6, longterm: 0.5 },
    price: 1, capacity: "large", bestWindows: W.brooklynLate, easyIn: 0.55,
    photo: P.forest, friendsBeen: 5,
  }),
  bar({
    slug: "the-commodore",
    attrs: { frozen: 1, food: 0.8, late: 1, cheap: 0.9 },
    name: "The Commodore",
    neighborhood: "williamsburg",
    address: "366 Metropolitan Ave, Brooklyn, NY 11211",
    lat: 40.7139, lng: -73.9536,
    take: "Frozen drinks, fried chicken, a dark room that's always a little too full; a Williamsburg rite of passage.",
    tags: ["Dive", "Lively", "Fried Chicken"],
    vibe: { lively: 0.9, chill: 0.4, talk: 0.2 },
    groupFit: { two: 0.7, small: 0.85, mid: 0.75, big: 0.45 },
    dateFit: { first: 0.5, early: 0.65, longterm: 0.6 },
    price: 1, capacity: "medium", bestWindows: W.brooklynLate, easyIn: 0.4,
    photo: P.plum, friendsBeen: 4,
  }),
  bar({
    slug: "maison-premiere",
    attrs: { outdoor: 1, food: 0.8, upscale: 0.7 },
    name: "Maison Premiere",
    neighborhood: "williamsburg",
    address: "298 Bedford Ave, Brooklyn, NY 11249",
    lat: 40.7143, lng: -73.9615,
    take: "Oysters, absinthe, a garden in back; New Orleans by way of Bedford Avenue, and the most romantic bar in the borough.",
    theCatch: "The garden fills first; put your name in and take the bar.",
    tags: ["Oysters", "Garden", "Date"],
    vibe: { lively: 0.5, chill: 0.75, talk: 0.7 },
    groupFit: { two: 0.95, small: 0.75, mid: 0.35, big: 0.1 },
    dateFit: { first: 0.9, early: 0.95, longterm: 0.9 },
    price: 3, capacity: "medium", bestWindows: W.cocktailHours, easyIn: 0.35,
    photo: P.forest, friendsBeen: 3,
  }),
  bar({
    slug: "skinny-dennis",
    attrs: { liveMusic: 1, frozen: 0.8, cheap: 0.9, late: 1, social: 0.7 },
    name: "Skinny Dennis",
    neighborhood: "williamsburg",
    address: "152 Metropolitan Ave, Brooklyn, NY 11249",
    lat: 40.7148, lng: -73.9629,
    take: "A honky-tonk with live country most nights and frozen coffee drinks; loud, cheap, and impossible not to enjoy.",
    tags: ["Live Music", "Honky-Tonk", "Groups"],
    vibe: { lively: 0.95, chill: 0.35, talk: 0.1 },
    groupFit: { two: 0.65, small: 0.85, mid: 0.85, big: 0.6 },
    dateFit: { first: 0.5, early: 0.65, longterm: 0.6 },
    price: 1, capacity: "medium", bestWindows: W.brooklynLate, easyIn: 0.45,
    photo: P.amber, friendsBeen: 2,
  }),
  bar({
    slug: "bar-blondeau",
    attrs: { rooftop: 0.9, upscale: 0.9, dressy: 0.6 },
    name: "Bar Blondeau",
    neighborhood: "williamsburg",
    address: "80 Wythe Ave, Brooklyn, NY 11249",
    lat: 40.722, lng: -73.9581,
    take: "Top of the Wythe, French-leaning, the skyline through big windows; the polished date bar on the north side.",
    tags: ["Views", "Cocktails", "Date"],
    vibe: { lively: 0.6, chill: 0.65, talk: 0.6 },
    groupFit: { two: 0.95, small: 0.75, mid: 0.4, big: 0.15 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "medium", bestWindows: W.cocktailHours, easyIn: 0.4,
    photo: P.ink, friendsBeen: 1,
  }),
  bar({
    slug: "radegast-hall",
    attrs: { beer: 1, seating: 1, food: 0.7, outdoor: 0.7, sports: 0.5, cheap: 0.6 },
    name: "Radegast Hall & Biergarten",
    neighborhood: "williamsburg",
    address: "113 N 3rd St, Brooklyn, NY 11249",
    lat: 40.716, lng: -73.9617,
    take: "Long tables, big beers, a retractable roof; the answer to 'there are eleven of us' every single time.",
    tags: ["Beer Hall", "Big Groups", "Easy"],
    vibe: { lively: 0.85, chill: 0.5, talk: 0.3 },
    groupFit: { two: 0.4, small: 0.7, mid: 0.9, big: 1.0 },
    dateFit: { first: 0.25, early: 0.35, longterm: 0.4 },
    price: 2, capacity: "large", bestWindows: W.everyNight, easyIn: 0.8,
    photo: P.brass, friendsBeen: 2,
  }),
  bar({
    slug: "clems",
    attrs: { cheap: 1, late: 1, activity: 0.3 },
    name: "Clem's",
    neighborhood: "williamsburg",
    address: "264 Grand St, Brooklyn, NY 11211",
    lat: 40.7126, lng: -73.9583,
    take: "A neighborhood dive with a good jukebox and no agenda; cheap, chill, and open late.",
    tags: ["Dive", "Chill", "Late"],
    vibe: { lively: 0.6, chill: 0.8, talk: 0.55 },
    groupFit: { two: 0.8, small: 0.85, mid: 0.6, big: 0.3 },
    dateFit: { first: 0.5, early: 0.65, longterm: 0.65 },
    price: 1, capacity: "medium", bestWindows: W.brooklynLate, easyIn: 0.7,
    photo: P.slate, friendsBeen: 1,
  }),
  bar({
    slug: "the-four-horsemen",
    attrs: { wine: 1, food: 0.9, upscale: 0.6 },
    name: "The Four Horsemen",
    neighborhood: "williamsburg",
    address: "295 Grand St, Brooklyn, NY 11211",
    lat: 40.7119, lng: -73.9575,
    take: "Natural wine and small plates in a room designed by people with taste; a date that's more conversation than cocktails.",
    theCatch: "Small and beloved; expect to wait for a table, less for the bar.",
    tags: ["Wine", "Can Actually Talk", "Date"],
    vibe: { lively: 0.45, chill: 0.8, talk: 0.85 },
    groupFit: { two: 0.95, small: 0.7, mid: 0.3, big: 0.05 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.9 },
    price: 3, capacity: "small", bestWindows: W.cocktailHours, easyIn: 0.3,
    photo: P.wine, friendsBeen: 2,
  }),
  restaurant({
    slug: "llama-inn",
    attrs: { rooftop: 0.7, outdoor: 0.6 },
    name: "Llama Inn",
    neighborhood: "williamsburg",
    address: "50 Withers St, Brooklyn, NY 11211",
    lat: 40.7163, lng: -73.9509,
    take: "Peruvian, festive, with a rooftop in season; a date dinner that's fun for four too.",
    tags: ["Peruvian", "Festive", "Rooftop"],
    vibe: { lively: 0.75, chill: 0.5, talk: 0.5 },
    groupFit: { two: 0.85, small: 0.9, mid: 0.6, big: 0.25 },
    dateFit: { first: 0.8, early: 0.85, longterm: 0.75 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.4,
    photo: P.rose, friendsBeen: 2,
  }),
  restaurant({
    slug: "lilia",
    name: "Lilia",
    neighborhood: "williamsburg",
    address: "567 Union Ave, Brooklyn, NY 11211",
    lat: 40.7175, lng: -73.952,
    take: "The reservation everyone wants and the pasta that justifies it; if you got the table, the date is already going well.",
    theCatch: "Reservations are famously hard; the walk-in bar is the only realistic play.",
    tags: ["Italian", "Occasion", "Pasta"],
    vibe: { lively: 0.7, chill: 0.5, talk: 0.55 },
    groupFit: { two: 0.9, small: 0.8, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.6, early: 0.9, longterm: 0.95 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.1,
    photo: P.amber, friendsBeen: 4,
  }),
  restaurant({
    slug: "diner",
    name: "Diner",
    neighborhood: "williamsburg",
    address: "85 Broadway, Brooklyn, NY 11249",
    lat: 40.7105, lng: -73.9654,
    take: "A dining car under the bridge with a chalkboard menu and real charm; the low-key date that ages well.",
    tags: ["American", "Date", "Under the Bridge"],
    vibe: { lively: 0.55, chill: 0.7, talk: 0.7 },
    groupFit: { two: 0.95, small: 0.75, mid: 0.35, big: 0.1 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.85 },
    price: 3, capacity: "small", bestWindows: W.dinner, easyIn: 0.4,
    photo: P.brass, friendsBeen: 2,
  }),

  // ───────────────────────── GREENPOINT ─────────────────────────
  restaurant({
    slug: "bernies",
    attrs: { social: 0.6, cocktails: 0.7 },
    name: "Bernie's",
    neighborhood: "greenpoint",
    address: "332 Driggs Ave, Brooklyn, NY 11222",
    lat: 40.7228, lng: -73.9516,
    take: "Red booths, mozzarella sticks, martinis: dinner that feels like a party and treats a group of six like regulars.",
    theCatch: "Waits on weekends; the bar in front is the move while you wait.",
    tags: ["American", "Groups", "Fun"],
    vibe: { lively: 0.85, chill: 0.45, talk: 0.4 },
    groupFit: { two: 0.75, small: 0.9, mid: 0.9, big: 0.5 },
    dateFit: { first: 0.7, early: 0.75, longterm: 0.7 },
    price: 2, capacity: "medium", bestWindows: W.dinner, easyIn: 0.35,
    photo: P.wine, friendsBeen: 3,
  }),
  bar({
    slug: "ramona",
    attrs: { dance: 0.3, late: 0.8 },
    name: "Ramona",
    neighborhood: "greenpoint",
    address: "113 Franklin St, Brooklyn, NY 11222",
    lat: 40.7305, lng: -73.9583,
    take: "High ceilings, good cocktails, a room that's lively on weekends and quietly perfect on a Tuesday.",
    tags: ["Cocktails", "Lively", "Date"],
    vibe: { lively: 0.7, chill: 0.6, talk: 0.5 },
    groupFit: { two: 0.85, small: 0.85, mid: 0.65, big: 0.35 },
    dateFit: { first: 0.75, early: 0.8, longterm: 0.75 },
    price: 2, capacity: "medium", bestWindows: W.brooklynLate, easyIn: 0.55,
    photo: P.plum, friendsBeen: 2,
  }),
  bar({
    slug: "achilles-heel",
    attrs: { classic: 0.8, outdoor: 0.5 },
    name: "Achilles Heel",
    neighborhood: "greenpoint",
    address: "180 West St, Brooklyn, NY 11222",
    lat: 40.7303, lng: -73.9591,
    take: "An old waterfront tavern with a wood stove and the best quiet in Greenpoint; for the conversation, not the crowd.",
    tags: ["Tavern", "Chill", "Can Actually Talk"],
    vibe: { lively: 0.35, chill: 0.9, talk: 0.9 },
    groupFit: { two: 0.95, small: 0.75, mid: 0.4, big: 0.1 },
    dateFit: { first: 0.8, early: 0.9, longterm: 0.9 },
    price: 2, capacity: "small", bestWindows: W.everyNight, easyIn: 0.6,
    photo: P.forest, friendsBeen: 1,
  }),
  bar({
    slug: "pencil-factory",
    attrs: { classic: 0.5, happyHour: 0.6, cheap: 0.8 },
    name: "Pencil Factory",
    neighborhood: "greenpoint",
    address: "142 Franklin St, Brooklyn, NY 11222",
    lat: 40.7316, lng: -73.9581,
    take: "A corner bar that's never trying too hard; good beer, decent room, easy for a group that just wants to sit.",
    tags: ["Corner", "Beer", "Chill"],
    vibe: { lively: 0.6, chill: 0.8, talk: 0.6 },
    groupFit: { two: 0.75, small: 0.85, mid: 0.75, big: 0.45 },
    dateFit: { first: 0.5, early: 0.65, longterm: 0.65 },
    price: 1, capacity: "medium", bestWindows: W.everyNight, easyIn: 0.7,
    photo: P.slate, friendsBeen: 1,
  }),
  bar({
    slug: "broken-land",
    attrs: { cheap: 0.7, late: 0.8 },
    name: "Broken Land",
    neighborhood: "greenpoint",
    address: "105 Franklin St, Brooklyn, NY 11222",
    lat: 40.7304, lng: -73.9583,
    take: "Cocktails in a bar that looks like a dive and drinks like a good one; unbothered, affordable, right.",
    tags: ["Cocktails", "Dive", "Chill"],
    vibe: { lively: 0.6, chill: 0.75, talk: 0.55 },
    groupFit: { two: 0.85, small: 0.85, mid: 0.6, big: 0.3 },
    dateFit: { first: 0.65, early: 0.75, longterm: 0.7 },
    price: 2, capacity: "small", bestWindows: W.brooklynLate, easyIn: 0.6,
    photo: P.night, friendsBeen: 1,
  }),
  restaurant({
    slug: "oxomoco",
    name: "Oxomoco",
    neighborhood: "greenpoint",
    address: "128 Greenpoint Ave, Brooklyn, NY 11222",
    lat: 40.7304, lng: -73.9556,
    take: "Wood-fired Mexican in a skylit room; a date dinner with energy and a mezcal list to get lost in.",
    tags: ["Mexican", "Wood-Fired", "Date"],
    vibe: { lively: 0.7, chill: 0.55, talk: 0.55 },
    groupFit: { two: 0.9, small: 0.85, mid: 0.5, big: 0.2 },
    dateFit: { first: 0.85, early: 0.9, longterm: 0.8 },
    price: 3, capacity: "medium", bestWindows: W.dinner, easyIn: 0.4,
    photo: P.amber, friendsBeen: 2,
  }),
];

/** Normalized seed — the fallback whenever no database is configured. */
export const SEED_VENUES: Venue[] = RAW.map(normalizeSeed).map((v) => {
  const hot = SEED_STORIES[v.slug];
  return hot ? { ...v, hot: true, hotRank: hot.rank, story: hot.story } : v;
});

/** @deprecated prefer getVenues() from lib/db — kept for the seed importer and tests. */
export const VENUES = SEED_VENUES;

export function venueMap(venues: Venue[]): Record<string, Venue> {
  return Object.fromEntries(venues.map((v) => [v.slug, v]));
}

/** The ten places the taste quiz swipes through — iconic, spread across the map. */
export const QUIZ_SLUGS = [
  "rays-bar",
  "dante-west-village",
  "death-and-co",
  "union-pool",
  "the-spaniard",
  "maison-premiere",
  "fanelli-cafe",
  "westlight",
  "attaboy",
  "the-commodore",
];
